# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Centered-block--demo"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:Left-right-block-component__heading-text
  media: ""
  external_url: ""
  use_external_url: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  media:
    type: file
  external_url:
    type: text
  use_external_url:
    type: switch