# Metadata about this component, to be used in the CMS
spec:
  structures:
    - left-right-block
  label: "Left-right-block-component__heading-text"
  description: Text with heading
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Hello World!"
  text: ""
  eyebrow: ""
  simple_components: [bookshop:structure:simple_components]


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: textarea