# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Block with bottom image"
  description: A block of content with an image on the bottom
  icon: vertical_align_bottom
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Hello World!"
  text: ""
  show_button: true
  button: bookshop:button!  

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: textarea