# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Button"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    text: "Hello World!"
  style:
    style: ""
    size: ""
    disabled: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  style:  
    comment: Choose either a primary or secondary colour scheme
    type: select
    options:
      values:
        - primary
        - secondary
  size:  
    comment: Choose either a small or large button size
    type: select
    options:
      values:
        - small
        - large