# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks    
  label: "Left-right block"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:  
  heading: ""
  left: bookshop:structure:left-right-block
  left_cols: 5
  right: bookshop:structure:left-right-block 
  right_cols: 6
  forceRightOnTop: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  left_cols: 
    type: range
    options:
      step: 1
      max: 6
      min: 5
  right_cols: 
    type: range
    options:
      step: 1
      max: 6
      min: 5