# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks    
  label: "Left-right block"
  description:
  icon: switch_left
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:  
  background: "white"
  left: [bookshop:structure:left-right-block]
  left_cols: 5
  right: [bookshop:structure:left-right-block]
  right_cols: 6
  forceRightOnTop: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background:
    type: array
    options:
      values: 
        - white
        - grey
  left:
    type: array
  right:
    type: array
  left_cols: 
    type: range
    options:
      step: 1
      max: 6
      min: 5
  right_cols: 
    type: range
    options:
      step: 1
      max: 6
      min: 5