# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left-right-block"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Hello World!"
  text: ""
  image: ""
  image_position: "left"
  show_button: true
  list_items: 
    - "Item 1"
    - "Item 2"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  list_items:
    type: array
  image_position:
  type: select
  options:
    values:
      - "left"
      - "right"